### PR TITLE
Set flex-direction: column on How does Drivechain improve...

### PR DESCRIPTION
**Pull request by ian-campbell**
Add `flex-direction: column` to the container div for "How does Drivechain improve..." and "Possible sidechains" columns on line 162 of index.html

### CODE REVIEW

**Comment by ian-campbell** [comment]
before/after columns
Screenshot 2023-09-26 at 3 20 00 AM


Screenshot 2023-09-26 at 3 19 53 AM

**Comment by ian-campbell** [comment]
I noticed these two columns had `width: "100%"` but were rendering as if they were 50% width. To fix that I added `flex-direction: column` to the parent container.

**Comment by fiatjaf** [comment]
But I wanted the site to have two columns, not two blocks of content one on the top of the other!

**Comment by ian-campbell** [comment]
> But I wanted the site to have two columns, not two blocks of content one on the top of the other!

Gotcha. I was wondering because each of the columns is set to 100% width so I thought full width columns were desired instead of half width as displayed

**Comment by fiatjaf** [comment]
We should have this for small screens.
But then we're getting into weird webdesign territory.
I'll try later nonetheless.

Thank you!

**Comment by ian-campbell** [comment]
> We should have this for small screens.
> 
> But then we're getting into weird webdesign territory.
> 
> I'll try later nonetheless.
> 
> 
> 
> Thank you!

I'll look into setting the columns just for mobile. Happy to help the drivechoin

**Comment by ian-campbell** [comment]
I changed it so that now the two columns only rearrange on smaller than 500px screens. I added two css classes 'mobileColumn' and 'possibleSidechains' and put them in the `main.css` @media query for mobile screens

**Pull request merged**
